export const informationDictionary = {
  eNPV: {
    title: "eNPV",
    description:
      "eNPV stands for Expected Net Present Value and is a measure of the value of your portfolio today, taking into account all its expected future costs and revenue. You will be ranked on the leaderboard based on your portfolio's average eNPV during the whole game.",
  },
  eROI: {
    title: "eROI",
    description:
      "eROI stands for Expected Return On Investment. This tells you the ratio of expected return (revenue - cost) to expected costs for your currently selected portfolio. A zero value means you've broken even.",
  },
  costCurve: {
    title: "Cost",
    description:
      "This plot shows the expected cost of your portfolio over the remaining time. The highlighted point is the cost of your current selection, which you will need to pay in order to progress to the next year.",
  },
  revenueCurve: {
    title: "Budget",
    description:
      "This plot shows the expected budget of your portfolio over the remaining time. Your budget is a percentage of the Sales you make from your drugs that are on the market. The highlighted point is the budget you will receive next year.",
  },
  capitalPlot: {
    title: "Capital",
    description:
      "This plot shows your capital over time, including the expected capital in the future. This is calculated based on the expected costs and funding (see Budget plot) you will receive. The highlighted point is your current position. Keep an eye out on when this line goes below zero, as you lose the game if you go bankrupt!",
  },
  knapsackAgent: {
    title: "Knapsack Agent",
    description:
      "The Knapsack agent is a single-step optimiser. That means it optimises for the highest eNPV you can get based on your current capital. It doesn't consider future costs or revenue.",
  },
  pyxieAgent: {
    title: "Pyxie Agent",
    description:
      "The Pyxie agent is a reinforcement learning, multi-step agent. It has learned an optimal strategy that plays out to maximise your eNPV this year and future years. Its suggestion on this step may only show you part of a larger strategy.",
  },
  alphainvestAgent: {
    title: "Pyxie Agent",
    description:
      "The Pyxie agent is a reinforcement learning, multi-step agent. It has learned an optimal strategy that plays out to maximise your eNPV this year and future years. Its suggestion on this step may only show you part of a larger strategy.",
  },
  TA: {
    title: "TA",
    description: "Therapeutic Area.",
  },
  phasePTRS: {
    title: "PTRS Estimate (%)",
    description:
      "Estimated Probability of Technical and Regulatory Success for the Current Phase. When distributional PTRS is enabled, shows the expected value with uncertainty bounds (p10-p90) and confidence level that improves as you gain experience in the therapeutic area.",
  },
  abandonAction: {
    title: "Abandon Development",
    description:
      "Permanently stops development of this asset. The asset will move to Failed state and cannot be restarted. Use this to cut losses when interim trial signals suggest the trial is likely to fail.",
  },
  remainingPhaseCost: {
    title: "Remaining Phase Cost",
    description: "Total remaining cost of the Current Phase",
  },
  PYS: {
    title: "PYS",
    description:
      "Peak Year Sales, the maximum sales that will be generated by the asset should it make it onto the market.",
  },
  PYS2: {
    title: "PYS",
    description:
      "Peak Year Sales, the maximum sales generated by the asset. Revenue increases until reaching PYS and stays here until patent expiry.",
  },
  timeFromLaunchToPYS: {
    title: "Time from launch to PYS",
    description:
      "The years from when it first launched to when it hits Peak Sales. Compare this to Time on Market to know if you are before or during Peak Sales.",
  },
  timeToExpiry: {
    title: "Time to Expiry",
    description: "Remaining years until patent expiry.",
  },
  budgetNextYear: {
    title: "Budget Next Year",
    description:
      "The Budget Next Year is a percentage of your Sales next year and will be added to your Capital when you progress to the next step.",
  },
  investmentLevels: {
    title: "Investment Levels",
    description:
      "Investment levels allow you to control the intensity of R&D investment for each asset. Higher investment levels increase costs but also speed up development and may improve success rates. Each level also uses R&D capacity - exceeding capacity will incur penalties.",
  },
  interimSignal: {
    title: "Interim Signal",
    description:
      "An early readout from the ongoing clinical trial. A positive signal (green) suggests the trial is trending towards success, while a negative signal (amber) indicates the trial may be struggling. Use this information to decide whether to continue investing or abandon the asset early to cut losses.",
  },
} as const;
