export const informationDictionary = {
  eNPV: {
    title: "eNPV",
    description:
      "eNPV stands for Expected Net Present Value and is a measure of the value of your portfolio today, taking into account all its expected future costs and revenue. You will be ranked on the leaderboard based on your portfolio's average eNPV during the whole game.",
  },
  cashEnpv: {
    title: "Cash eNPV",
    description: "eNPV with sales scaled by the reinvestment rate (35%).",
  },
  eROI: {
    title: "eROI",
    description:
      "eROI stands for Expected Return On Investment. This tells you the ratio of expected return (revenue - cost) to expected costs for your currently selected portfolio. A zero value means you've broken even.",
  },
  costCurve: {
    title: "Cost",
    description:
      "This plot shows the expected cost of your portfolio over the remaining time. The highlighted point is the cost of your current selection, which you will need to pay in order to progress to the next year.",
  },
  revenueCurve: {
    title: "Budget",
    description:
      "This plot shows the expected budget of your portfolio over the remaining time. Only the reinvestment rate (35%) of sales reaches your Capital. The highlighted point is the budget you will receive next year.",
  },
  capitalPlot: {
    title: "Capital",
    description:
      "This plot shows your capital over time, including the expected capital in the future. This is calculated based on the expected costs and funding (see Budget plot) you will receive. The highlighted point is your current position. Keep an eye out on when this line goes below zero, as you lose the game if you go bankrupt!",
  },
  knapsackAgent: {
    title: "Knapsack Agent",
    description:
      "The Knapsack agent is a single-step optimiser. That means it optimises for the highest eNPV you can get based on your current capital. It doesn't consider future costs or revenue.",
  },
  TA: {
    title: "TA",
    description: "Therapeutic Area.",
  },
  phasePTRS: {
    title: "PTRS Estimate (%)",
    description:
      "Estimated Probability of Technical and Regulatory Success for the Current Phase.",
  },
  abandonAction: {
    title: "Abandon Development",
    description:
      "Permanently stops development of this asset. The asset will move to Failed state and cannot be restarted. Use this to cut losses when a trial is likely to fail.",
  },
  remainingPhaseCost: {
    title: "Remaining Phase Cost",
    description: "Total remaining cost of the Current Phase",
  },
  PYS: {
    title: "PYS",
    description:
      "Peak Year Sales, the maximum sales that will be generated by the asset should it make it onto the market.",
  },
  PYS2: {
    title: "PYS",
    description:
      "Peak Year Sales, the maximum sales generated by the asset. Revenue increases until reaching PYS and stays here until patent expiry.",
  },
  timeFromLaunchToPYS: {
    title: "Time from launch to PYS",
    description:
      "The years from when it first launched to when it hits Peak Sales. Compare this to Time on Market to know if you are before or during Peak Sales.",
  },
  timeToExpiry: {
    title: "Time to Expiry",
    description: "Remaining years until patent expiry.",
  },
  budgetNextYear: {
    title: "Budget Next Year",
    description:
      "The cash this asset adds to your Capital next step: gross sales scaled by the reinvestment rate (35%).",
  },
} as const;
